#!/usr/bin/env bash

eval $(ssh-agent)

ssh-add ~/.ssh/school

ssh ubuntu@18.208.119.174 << 'EOF'

# Firewall setup commands
sudo ufw status
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw show added
sudo ufw enable

EOF
