#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5

for c in {1..100}
do
if ((c % 15 == 0))
    then
    echo "FizzBuzz"
elif ((c % 5 == 0))
    then
    echo "Buzz"
elif (( c % 3 == 0))
    then
    echo "Fizz"
else
    echo "$c"
fi
done
